
submit_ticket:
    path:     /tickets/submit
    defaults: { _controller: AppBundle:Sales:submitTicket }

ticket_submission_successful:
    path:     /tickets/submit/success
    defaults: { _controller: AppBundle:Sales:ticketSubmissionSuccessful }

member_sign_up:
    path:     /members/signup
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Members:signUp }

member_sign_up_successful:
    path:     /members/signup/successful
    defaults: { _controller: AppBundle:Members:signUpSuccessful }

member_sign_in:
    path:     /members/signin
    defaults: { _controller: AppBundle:Members:signIn }

member_sign_out:
    path:     /members/signout
    defaults: { _controller: AppBundle:Members:signOut }

admin.list_all_tickets:
  path: /admin/tickets/all
  defaults: { _controller: AppBundle:Admin\Tickets:listAllTickets }

admin.list_buy_tickets:
  path: /admin/tickets/buy
  defaults: { _controller: AppBundle:Admin\Tickets:listForBuyingTickets }

admin.list_sell_tickets:
  path: /admin/tickets/sell
  defaults: { _controller: AppBundle:Admin\Tickets:listSellTickets }


admin.proposition.ticket:
  path: /admin/tickets/proposition/{index}
  defaults: { _controller: AppBundle:Admin\Tickets:PropositionTicket }